### ISSUE TITLE
Publish the results in a csv file

### ISSUE THREAD

**Issue by sbryfcz** [Jaid/serialize-comparison#1]
It would be great if you published the results to a CSV file for others to use. I'd like to create a scatterplot of the data to help highlight the differences. I know I could create it myself...but publishing one would be really convenient.

Nice work.

**Comment by Jaid** [comment]
CSV export is available now.

```bash
npx serialize-comparison --csv report.csv
```

I uploaded a CSV file to the [Releases page](https://github.com/Jaid/serialize-comparison/releases).
